#!/bin/bash

declare -A visited_dirs

# Function to recursively display directory content
display_dir_content() {
    local dir_path=$1
    local prefix=$2
    local files=("$dir_path"/*)
    local total=${#files[@]}

    visited_dirs["$dir_path"]=1

    for ((i = 0; i < total; i++)); do
        file="${files[$i]}"
        base_name=$(basename "$file")
        if [ $i -eq $(($total - 1)) ]; then
            connector="└──"
            new_prefix="$prefix\t"
        else
            connector="├──"
            new_prefix="$prefix│\t"
        fi

	# object is een directory
        if [ -d "$file" ]; then
            if [[ -L "$file" ]]; then
                echo "${prefix}${connector} $base_name -> $(readlink "$file")"
            elif [[ -z "${visited_dirs["$file"]}" ]]; then
                echo -e "${prefix}${connector} $base_name"
                display_dir_content "$file" "$new_prefix"
            else
		# we've already processed this, so just continue
                echo "${prefix}${connector} $base_name [Already Visited]"
            fi
        else
            echo -e "${prefix}${connector} $base_name"
            while IFS= read -r line; do
                echo -e "${new_prefix}>> $line"
            done < "$file"
        fi
    done
}

# Starting point of the script
start_dir="."
display_dir_content "$start_dir" ""
